[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
Start Command: uvicorn main:app --host 0.0.0.0 --port $PORT

[variables]
PYTHONUNBUFFERED = "1"

[env]
root = "server"
